### ISSUE TITLE
WebFontLoader not working on Chrome for Android

### ISSUE THREAD

**Issue by ajck** [typekit/webfontloader#289] opened 2015-11-21 16:06 UTC
I'm using the code below on latest Google Chrome (v46 but also tried v45) on Android 4.1.1 and it always reports font inactive without fail for every font, though the same code works fine via Opera browser and native browser on Android, and on Safari 9 on an iPhone 4 and every major browser on Windows 7.

Behaviour is that on other browsers font loads (over fast wifi) in a second or two. On Android Chrome the fontloading event fires and then after the full timeout has expired, the fontinactive event fires.

I assume this is a bug in WFL or Chrome. Anyone know a workaround please?

    <html>
    <head>
    </head>
    <body>
        <div id="maincontent">
		<h1>Hello there</h1>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js"></script>
    <script>

    var somefonts = ['Capriola','Cardo','Carme','Carrois Gothic','Carrois Gothic SC','Carter One','Catamaran','Caudex','Caveat','Caveat Brush','Cedarville Cursive','Ceviche One'];

    var font = somefonts[Math.floor(Math.random() * 12)];
    alert('font: ' + font);

      WebFont.load({
        google: { families: [font] },
	    timeout: 30000, // 30 secs to make sure it's not a weird timeout issue
	    fontloading: function(familyName, fvd) { alert('fontloading: ' + familyName + ', ' + fvd); },
	    fontactive: function(familyName, fvd) { alert('fontactive: ' + familyName + ', ' + fvd);     
                    $("#maincontent").css('font-family', familyName); },
	    fontinactive: function(familyName, fvd) { alert('fontinactive: ' + familyName + ', ' + fvd); }
	});

    </script>
    </body>
    </html>

Many thanks,
Alex

**Comment by dancap-adroll** [comment] 2015-12-09 19:10
Hey Alex, we noticed an issue where the dynamic CSS link wasn't being written when the <head> element was empty ... maybe try putting a <title> in yours and see if that helps.

**Comment by ajck** [comment] 2015-12-09 23:28
Thanks. Just tried that, makes no difference at all. The exact same code works perfectly on the same Android tablet on Opera, Firefox and the native browser...

**Comment by ajck** [comment] 2015-12-18 16:16
Any thoughts anyone? This is still outstanding and not an insignificant platform...
Thanks!

**Comment by mhmli** [comment] 2015-12-18 18:17
@ajck The GitHub version is several versions newer than 1.5.18. Try using the latest version, that helped me to solve other problems.

**Comment by ajck** [comment] 2015-12-18 23:54
@mhmli good idea, thanks. Yes I thought that might help so I got the latest version but unfortunately not. I now get fontloading event firing as previously but then the fontinactive fires immediately, ignoring the timeout. I'm still using the code from my first post above. Whole thing works fine in latest Android Opera and native Android 4.1.1 browser.

Pretty crazy as this is the only thing stopping the web app I'm building from working fine on Android Chrome!

**Comment by ajck** [comment] 2016-01-10 00:21
OK, after a lot of research and testing and trying different fixes, I've finally found what the problem is.
It seems Chrome (latest few versions at least) on Android 4.1.1 (at least, maybe other versions too) will only load any web font if the CSS for @font-face definition is in the actual HTML page that's displaying it, it can't be a remote file. This is even when not using web font loader, it's just with any Google font (haven't tried with other web fonts).
So putting this in the page head:

    <link href='http://fonts.googleapis.com/css?family=Courgette' rel='stylesheet' type='text/css'>

doesn't work - nothing happens and the font doesn't load.
But following that link and grabbing the CSS from it and pasting it into the page instead, works fine:

    <style type="text/css">
    @font-face {
      font-family: 'Courgette';
      font-style: normal;
      font-weight: 400;
      src: local('Courgette Regular'), local('Courgette-Regular'), url(https://fonts.gstatic.com/s/courgette/v4/BHG8ZtTfO0yYnp02--QxqltXRa8TVwTICgirnJhmVJw.woff2) format('woff2');
      unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
    }
    h1 { font-family: 'Courgette', cursive; }
    </style>
    </head>
    <body>
    <h1>Hello there</h1>
    </body>

Now I just have to work out how to get this working in my code with WebFontLoader for any dynamically specified Google Font

@bramstein maybe a work around could be incorporated in WFL somehow please?

Thanks.

**Comment by bramstein** [comment] 2016-01-25 23:22
@ajck I tested the latest Chrome on Android, and I can't reproduce the issue you're describing. Are you sure that is the root cause? If it were, a lot of sites would be broken.

**Comment by bramstein** [comment] 2016-02-29 09:01
Closing this issue because I can't reproduce it and there has been no new reports since a month. Feel free to re-open it if you're still experiencing the same issue.

**Closed by bramstein** 2016-02-29 09:01 UTC
