### ISSUE TITLE
wf-loading not being removed

### ISSUE THREAD

**Issue by monsterlane** [typekit/webfontloader#310] opened 2016-02-12 14:08 UTC
Sometimes when loading fonts wf-loading is not removed and 2-3 of the 6-8 fonts I load stick as font-loading. Since wf-loading is never removed the page looks blank. Lato seems to be one that fails more often then others.

Why isn't the error handler called and wf-loading removed? Any idea why randomly some fonts simply fail to load but refreshing a few times and they do?

**Comment by bramstein** [comment] 2016-02-17 14:09
That sounds weird. Do you have a test page somewhere so I can take a look? Also, if you could write down steps to reproduce the issue, that would be perfect.

**Comment by ktopping** [comment] 2016-02-22 14:47
@monsterlane are you seeing this across all browsers? I am seeing a [very similar issue](https://github.com/typekit/webfontloader/issues/298#issuecomment-185973025) almost exclusively on Firefox.

**Comment by monsterlane** [comment] 2016-02-22 14:56
I've only been able to reproduce it in Firefox, can't provide a test case as it's a live website and I had to add a timer to remove wf-loading when this script fails to remove it.

**Comment by ktopping** [comment] 2016-02-22 15:03
Yeah that's exactly what I've done. Along the lines of:

```javascript
  window.setTimeout(function () {
    if ($("html").hasClass("wf-loading")) {
      $("html").removeClass("wf-loading");
    }
  }, 5000);
```

**Comment by monsterlane** [comment] 2016-02-22 15:17
Same, I'm using:

```
  window.setTimeout(function () {
      $("html.wf-loading").removeClass("wf-loading");
  }, 3000);
```

**Comment by creole** [comment] 2016-02-22 15:38
Same issue here, also on Firefox.

**Comment by bramstein** [comment] 2016-02-22 16:01
That should definitely not happen, I'll look into it. Does anyone have a test page I can take a look at, or does this happen with all fonts/WFL on Firefox?

**Comment by ktopping** [comment] 2016-02-23 09:25
Hi @bramstein I have a url that exhibits the issue; I will send it to you off-list.
Basically it's a page from our staging server, running our code WITHOUT the above fix. I tried systematically removing javascript/css/html to try to find a simpler test case. However what seems to happen is that the more code I remove, the harder the issue is to reproduce. With what I'm sending you, the issue occurs within a few reloads. Once I started removing code, it would takes 10's, even 100's of reloads to reproduce.

**Comment by bramstein** [comment] 2016-02-29 12:48
Thanks for reporting this. I think I fixed this issue in v1.6.22. Could you give that version a try and see if the issue is resolved? Thanks!

**Comment by creole** [comment] 2016-02-29 14:53
Looks good :-)

**Comment by bramstein** [comment] 2016-02-29 16:21
Thanks for confirming. I'll close this issue, but feel free to re-open it if you're still experiencing problems.

**Closed by bramstein** 2016-02-29 16:21 UTC

**Comment by circularone** [comment] 2016-03-25 10:55
I'm still seeing this issue in Firefox on the latest version. For me it only happens with italic fonts.

**Comment by rku4er** [comment] 2016-05-12 18:07
I can confirm issue in latest Firefox (using https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js)
