### ISSUE TITLE
Firefox 44.0.2 - Inactive

### ISSUE THREAD

**Issue by paullowther** [typekit/webfontloader#312] opened 2016-02-15 08:51 UTC
Latest version of Firefox (44.0.2) causing the webfontloader to set class of inactive and fall back on stack. 

[http://www.eframe.co.uk/] (Example - must be opened in the latest version of FF 44.0.2)

**Comment by bramstein** [comment] 2016-02-17 14:08
The fonts on your site appear to be loading correctly. Are you still seeing this issue?

**Comment by nextend** [comment] 2016-02-26 11:01
I have the same issue, but most of the times it loads. To reproduce this issue:

- Open a test site where font loading happens with multiple font.
- Open a page on a new tab, doesn't matter what
- Go back to the test page, hit CTRL+F5 and switch to the other tab
- When you switch back to the original tab, some fonts might be not loaded. If everything is fine, try the previous steps again and again.

Here are my classes when the fonts loaded:
`wp-toolbar supports csstransforms3d csstransformspreserve3d wf-montserrat-n4-active wf-montserrat-i2-active wf-montserrat-n3-active wf-montserrat-i6-active wf-sourcesanspro-n3-active wf-sourcesanspro-n4-active wf-merriweather-n4-active wf-merriweather-i6-active wf-raleway-n4-active wf-vollkorn-i2-active wf-vollkorn-n3-active wf-vollkorn-n4-active wf-vollkorn-i6-active wf-sourcesanspro-i2-active wf-sourcesanspro-i6-active wf-merriweather-i2-active wf-merriweather-n3-active wf-raleway-n3-active wf-raleway-i2-active wf-raleway-i6-active wf-active`

and when some of them not loaded with the described technique:
`wp-toolbar supports csstransforms3d csstransformspreserve3d wf-loading wf-sourcesanspro-i2-loading wf-sourcesanspro-i6-loading wf-merriweather-i2-loading wf-merriweather-n3-loading wf-raleway-i2-loading wf-raleway-n3-loading wf-raleway-i6-loading wf-montserrat-n4-active wf-montserrat-i2-active wf-montserrat-n3-active wf-montserrat-i6-active n2-in-expert wf-sourcesanspro-n3-active wf-merriweather-n4-active wf-merriweather-i6-active wf-sourcesanspro-n4-active wf-vollkorn-i2-active wf-vollkorn-n3-active wf-vollkorn-n4-active wf-vollkorn-i6-active wf-raleway-n4-active`

In Firebug on the network tab, every font seems OK in the Google CSS. 

Also I found if I disable the API for the Fontwatcher, then it works fine.

You can do this by opening: /src/core/fontwatcher.js and there is the version 42 hardcoded:
`FontWatcher.SHOULD_USE_NATIVE_LOADER = parseInt(match[1], 10) > 42;`
I  just replaced it with 100.

(you can also find this 42 in the minified version: (x=/Gecko.*Firefox\/(\d+)/.exec(window.navigator.userAgent))?42)

**Comment by bramstein** [comment] 2016-02-29 12:48
Thanks for reporting this. I think I fixed this issue in v1.6.22. Could you give that version a try and see if the issue is resolved? Thanks!

**Comment by nextend** [comment] 2016-02-29 12:57
Thanks, I just did some tests and it works fine where 1.6.21 failed. I just notice a strange effect with this update, sometimes when you follow my steps and change back to the tab where the font should be loaded, it marks all fonts loaded after 0,5-1 sec. (I'm running a spinner while the fonts are loading and this spinner stays for 0,5-1 sec after I switch back to the page.) It does not happen every time, but little frustrating. I know that it is not a real world use case, but maybe it indicates problem with the implementation.

**Comment by bramstein** [comment] 2016-02-29 16:22
@nextend Glad that fixed it. The new issue sounds weird. Do you have a test case somewhere?

(I'm closing this issue, but feel free to open a new one for that issue).

**Closed by bramstein** 2016-02-29 16:22 UTC
