### ISSUE TITLE
Webfont.load does not load same font again, with different subset

### ISSUE THREAD

**Issue by jashwant** [typekit/webfontloader#255] opened 2015-06-24 21:15 UTC
I am dynamically loading google fonts, based on user choice.

e.g. if user chooses `open sans` font with font style `regular` and subset `latin`, I load it like this.

````javascript
WebFont.load({
	google: {
		families: ['Open Sans:regular:latin']
	}
});
````

Now, if later, user changes from `regular` to `italic`, I do,

````javascript
WebFont.load({
	google: {
		families: ['Open Sans:italic:latin']
	}
});
````

...and this works perfectly.

But, when user changes the subset from `latin` to `cyrillic-ext`, and I do,

````javascript
WebFont.load({
	google: {
		families: ['Open Sans:regular:cyrillic-ext']
	}
});
````

It doesn't work. I don't even see any request in `Network` tab of console.

Is it a bug, or am I doing something wrong ?

**Comment by thomaspark** [comment] 2015-07-29 15:33
I'm having a similar issue except different weights and styles don't seem to be working either. This is happening in Chrome and Safari (Firefox works as intended).

Here's a demo: http://jsbin.com/nuxalifavi/edit?html,css,js,output

When clicking "Run with JS", only Open Sans 400 is loaded, which is used for all three Open Sans weights. So far so good.

But after clicking "Click Me", all three weights plus Oswald should be loaded, but only Oswald is downloaded. Commenting out the first `WebFont.load()`, or even just modifying the CSS (adding some whitespace) gets it working.

**Comment by jashwant** [comment] 2015-07-30 07:15
@thomaspark , `even just modifying the CSS (adding some whitespace) gets it working`, can you give me an example ?

**Comment by thomaspark** [comment] 2015-07-30 20:52
Here's an example. It fixes both Chrome and Safari.
http://jsbin.com/naruwupinu/1/edit?html,css,js,output

**Comment by bramstein** [comment] 2015-09-22 11:43
I think this is related to a bug I reported to Chrome a while back:

https://code.google.com/p/chromium/issues/detail?id=488801

The bug fails to render fonts within the same family if one font in the family has already been rendered. This has been fixed in Chrome and should hit stable soon.

**Closed by bramstein** 2015-09-22 11:43 UTC
